version: '3.7'
services:

  rtl_tcp:
    image: librtlsdr
    container_name: rtl_tcp
    devices:
      - /dev/bus/usb:/dev/bus/usb
    restart: unless-stopped
    command: rtl_tcp -a 0.0.0.0

  metermon:
    image: seanauff/metermon:arm
    container_name: metermon
    depends_on: rtl_tcp
    environment:
      - MQTT_BROKER_HOST=127.0.0.1
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_ID=metermon
      #- MQTT_USERNAME=user
      #- MQTT_PASSWORD=pass
      - MQTT_TOPIC_PREFIX=metermon
      - RTL_TCP_SERVER=rtl_tcp:1234
      - RTLAMR_MSGTYPE=all
      #- RTLAMR_FILTERID=
      #- RTLAMR_SYMBOLLENGTH=72
      - RTLAMR_UNIQUE=true
      - METERMON_SEND_RAW=false
      - METERMON_SEND_BY_ID=false
      #- METERMON_ELECTRIC_DIVISOR=100.0
      #- METERMON_WATER_DIVISOR=10.0
    restart: unless-stopped
